@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

GET  http://{{host}}/pessoas
Content-Type: :{{contentType}}

###
POST http://{{host}}/pessoas
Content-Type: :{{contentType}}

{
  "pessoa_id": "1",
  "nome": "jao",
  "dataNascimento": "12/02/1258",
  "cpf": "123456789",
  "ativo": "true",
  "meta": 10000
}

###
DELETE  http://{{host}}/pessoas/88
Content-Type: :{{contentType}}



